// IDD
#define	SP_SURFACE_PAINTER_IDD 253943

// main event control, it catches every mouse actions
#define	SP_SURFACE_PAINTER_EVENT_CTRL 10

// left panel with modes and options
#define SP_SURFACE_PAINTER_LEFT_PANEL_EVENT_ENTER_CTRL 110
#define SP_SURFACE_PAINTER_LEFT_PANEL_EVENT_EXIT_CTRL 111
#define	SP_SURFACE_PAINTER_LEFT_PANEL_CTRL_GROUP 15
#define	SP_SURFACE_PAINTER_MODES_LIST 11
#define	SP_SURFACE_PAINTER_OPTIONS_BACKGROUND 14

// notifications
#define SP_SURFACE_PAINTER_NOTIFICATIONS_CTRL_GROUP 16
