#define SP_MENU_W		pixelW * 16

// generics
/*
#define SP_FOLDED_W		pixelW * 40 * safeZoneW
#define SP_UNFOLDED_W	(0.15 + SP_FOLDED_W)
#define SP_MARGIN_X		0.01
#define SP_MARGIN_Y		0.015
#define SP_CONTENT_H	0.025

// modes
#define SP_MODES_W		SP_FOLDED_W
#define SP_MODES_H		(SP_CONTENT_H * 1.5)
#define SP_OPTIONS_W	0.15

// options
#define SP_OPTIONS_CONTENT_W			(SP_UNFOLDED_W - SP_FOLDED_W - SP_MARGIN_X * 2)
#define SP_OPTION_CONTENT_H				0.028
#define SP_OPTION_CONTENT_M				0.025
#define SP_OPTION_CONTENT_M_1_6TH		SP_OPTION_CONTENT_M / 6

#define SP_OPTION_HEADER_TEXT_H_DIVIDER	31
#define SP_OPTION_TITLE_TEXT_H_DIVIDER	40
#define SP_OPTION_COMMON_TEXT_H_DIVIDER	48
#define SP_OPTION_BUTTON_TEXT_H_DIVIDER	35
#define SP_OPTION_EDIT_EDIT_W			0.2
#define SP_OPTION_EDIT_TEXT_W			0.8

// notifications
#define SP_NOTIFICATION_W				0.3
#define SP_NOTIFICATION_H				0.035
#define SP_NOTIFICATION_MARGIN			pixelH * 2
*/