#define SP_SURFACE_PAINTER_POOL_EVENT_ENTER_CTRL 30
#define SP_SURFACE_PAINTER_POOL_EVENT_EXIT_CTRL 31
#define SP_SURFACE_PAINTER_POOL_BACKGROUND 32
#define SP_SURFACE_PAINTER_POOL_PANEL_CTRL_GROUP 33
#define SP_SURFACE_PAINTER_POOL_SEARCH_FIELD 34
#define SP_SURFACE_PAINTER_POOL_SEARCH_RESULT_LIST 35
#define SP_SURFACE_PAINTER_POOL_LIST 36

#define ENTRY_IDC_BEGINNING 100
#define ENTRY_PICTURE 3
#define ENTRY_BACKGROUND 18
#define ENTRY_DISPLAY_NAME 4
#define ENTRY_CLASS_NAME 5
#define ENTRY_OPEN_CLOSE 6
#define ENTRY_REMOVE 7
#define ENTRY_SETTINGS 8

#define ENTRY_PROBABILITY 9
#define ENTRY_PROBABILITY_EDIT 10

#define ENTRY_Z_OFFSET 11
#define ENTRY_Z_OFFSET_EDIT 12

#define ENTRY_SCALE 13
#define ENTRY_SCALE_EDIT_MIN 14
#define ENTRY_SCALE_EDIT_MAX 15

#define ENTRY_FOLLOW_TERRAIN 16
#define ENTRY_FOLLOW_TERRAIN_CHECKBOX 17
