#include "..\sp_core\sizes.hpp"

#define SP_POOL_FOLDED_X	(1 - SP_FOLDED_W)
#define SP_POOL_UNFOLDED_X	(1 - SP_UNFOLDED_W)
#define SP_POOL_CONTENT_W	(SP_UNFOLDED_W - SP_MARGIN_X * 2)

#define SP_POOL_SEARCH_H	SP_OPTION_CONTENT_H
#define SP_POOL_RESULT_H	SP_OPTION_CONTENT_H * 12
#define SP_POOL_POOL_H		0.4
#define SP_POOL_SEARCH_Y	SP_OPTION_CONTENT_M
#define SP_POOL_RESULT_Y	(SP_POOL_SEARCH_Y + SP_POOL_SEARCH_H + SP_OPTION_CONTENT_M_1_6TH)
#define SP_POOL_POOL_Y		(SP_POOL_RESULT_Y + SP_POOL_RESULT_H + SP_OPTION_CONTENT_M)

#define SP_POOL_ENTRY_H					SP_OPTION_CONTENT_H
#define SP_POOL_ENTRY_M					pixelH * 2
#define SP_POOL_ENTRY_TEXT				0.7
#define SP_POOL_ENTRY_PROBABILITY		0.2
#define SP_POOL_ENTRY_DELETE			0.1
#define SP_POOL_ENTRY_TEXT_BACKGROUND 	[0, 0, 0, 0.2]

#define SP_POOL_S_H	0.03
